### signup as jodi
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "Jodi",
  "lastName": "Chan",
  "email": "jodi1@gmail.com",
  "password": "123",
  "isAdmin": true
}

### signup as vik
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "Vik",
  "lastName": "Srivasata",
  "email": "vik@gmail.com",
  "password": "123"
}
### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "vik@gmail.com",
  "password": "123w"
}